-- 코드를 입력하세요
SELECT UG.USER_ID,UG.NICKNAME,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS UG, USED_GOODS_BOARD AS UB
WHERE UG.USER_ID = UB.WRITER_ID
AND UB.STATUS = 'DONE'
GROUP BY UG.USER_ID
HAVING TOTAL_SALES >=700000
ORDER BY TOTAL_SALES;