-- 코드를 입력하세요
SELECT UB.TITLE,UB.BOARD_ID,UR.REPLY_ID,UR.WRITER_ID,UR.CONTENTS,DATE_FORMAT(UR.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as UB,USED_GOODS_REPLY as UR
WHERE UB.BOARD_ID = UR.BOARD_ID
AND DATE_FORMAT(UB.CREATED_DATE,'%Y-%m-%d') between '2022-10-01' and '2022-10-31'
ORDER BY UR.CREATED_DATE ,UB.TITLE ASC;